uint8 msg_type
metacontrol_kb_msgs/Entity entity

metacontrol_kb_msgs/Attribute[] attributes
metacontrol_kb_msgs/Entity[] entities
metacontrol_kb_msgs/Relationship[] relationships
---
bool success

uint8 msg_type
metacontrol_kb_msgs/Entity entity
metacontrol_kb_msgs/Attribute[] attributes
metacontrol_kb_msgs/Entity[] entities
metacontrol_kb_msgs/Relationship[] relationships
